baseURL = "https://www.silviuvulcan.ro/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Silviu Vulcan · Landing Page"

_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Silviu Vulcan"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = "Landing Page"
  bio = "DevOps Engineer.  \nOpen source, technology, photography and travel Enthusiast."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    # the default fontawesome style in simple key-value pairs is "fab", i.e. brand icons
#    instagram = "https://instagram.com/jdoe"
#    twitter = "https://twitter.com/jdoe"
     linkedin = "https://www.linkedin.com/in/silviuvulcan/"
    
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
#    0 = { name = "ello", icon = "ello", style = "fab", link = "" } # empty links are possible

<<<<<<< HEAD
    0 = { name = "Blog", icon = "blog", style = "fas", link = "https://silviuvulcan.ro/blog" }
    1 = { name = "GitHub", icon = "github", style = "fab", link = "https://github.com/filviu/" }
    2 = { name = "fosstodon.org", icon = "mastodon", style = "fab", link = "https://fosstodon.org/@filviu", rel-me = true }
#    3 = { name = "mastodon.social", icon = "mastodon", style = "fab", link = "https://mastodon.social/@filviu", rel-me = true }
=======
[params.social]
  Github        = "filviu"
  LinkedIn      = "silviuvulcan"
  RSS           = "https://silviuvulcan.ro/blog/index.xml"
  Mastodon      = "@filviu@mastodon.social"
  blog          = "https://silviuvulcan.ro/blog/"
#  Email         = "email@example.com"
#  Twitter       = "silviuvulcan"
#  Stackoverflow = "username"
#  Medium        = "username"
#  Telegram      = "username"
#  Instagram     = "silviu.vulcan"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
#[[menu.main]]
#  name = "projects"
#  identifier = "projects"
#  weight = 200
#  url = "/projects/"
#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 300
#  url = "/resume/"
>>>>>>> 91ae39f974af5542976c168488337a6320b20bda
